services:
  - type: web
    name: new-api
    runtime: image
    image:
      url: docker.io/calciumion/new-api:latest
    plan: free
    envVars:
      - key: SQL_DSN
        value: postgresql://postgres.dneeirrqhorhhrygxxzs:6Ge%2Fuw2%2CXCNCDpB@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
      - key: SESSION_SECRET
        generateValue: true
      - key: TOKEN_SECRET
        generateValue: true
      - key: TZ
        value: Asia/Shanghai
