services:
  - type: web
    name: new-api
    runtime: image
    image:
      url: docker.io/calciumion/new-api:latest
    plan: free
    envVars:
      - key: SQL_DSN
        value: postgresql://postgres:6Ge%2Fuw2%2CXCNCDpB@db.dneeirrqhorhhrygxxzs.supabase.co:5432/postgres
      - key: SESSION_SECRET
        generateValue: true
      - key: TOKEN_SECRET
        generateValue: true
      - key: TZ
        value: Asia/Shanghai
